#!/usr/bin/env bash

DOTFILES_ROOT=~/.dotfiles

# Create symlink for O
omzssrc="$DOTFILES_ROOT"/".oh-my-zsh"
omzsdst="$HOME"/".oh-my-zsh"
ln -s $omzssrc $omzsdst

DOTFILES=`find "$DOTFILES_ROOT" -type f -maxdepth 1`
 
for src in $DOTFILES
do
    filename=$(basename $src)
    if [[ "$filename" != ".DS_Store" && "$filename" != ".dotfiles" && "$filename" != "scripts" && "$filename" != ".oh-my-zsh" && "$filename" != ".git" ]]
    then
        dst="$HOME/$filename"

        if [ -e $dst ]
        then
            echo "Backing up existing file: "$dst
            if [ -e $dst.backup ]
            then
            echo    rm -f $dst.backup
            fi
            echo mv -f $dst $dst.backup
        fi
        # echo $src $dst
        ln -s $src $dst
    else
        echo "Skipping "$filename
    fi
done
